sudo: required
services:
  - docker

before_install:
  - docker build -t jeffreyzhu/test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true jeffreyzhu/test npm test

after_success:
  - docker build -t jeffreyzhu/client ./client
  - docker build -t jeffreyzhu/nginx ./nginx
  - docker build -t jeffreyzhu/server ./server
  - docker build -t jeffreyzhu/worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push to docker hub
  - docker push jeffreyzhu/client 
  - docker push jeffreyzhu/nginx
  - docker push jeffreyzhu/server 
  - docker push jeffreyzhu/worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: fibonacci-calculator
  env: FibonacciCalculator-env-1
  bucket_name: elasticbeanstalk-us-east-2-936490621422
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY